[[GSL]]
arch = "aarch64"
git-tree-sha1 = "a393d0122d64871228c2439980745148d17b7937"
os = "macos"

    [[GSL.download]]
    sha256 = "dfae7447630fa6f5dc6520cf909f1c1e6684e0dd1a80724a9acbef31b853c93f"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.aarch64-apple-darwin.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "16569a689b9956ec55475f092a3692014fefd573"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "0c8de40041527c088d1af4d028270fd8843e6564dd3f766590189c2991141886"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.aarch64-linux-gnu.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "eb20bda7646b8b27e33b4f98180a7c9f61e38ce3"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "8973edff751bef0cc8bbc420812cf31bc645dbaa35c4ac62e9f242d833894813"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.aarch64-linux-musl.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "8bdeff1c386d1f9ef69a570ad7c664c2bb6d6d59"
os = "freebsd"

    [[GSL.download]]
    sha256 = "6bf217bdd347accb5b2db580507236632a3a0265957276405882c9efeb70a147"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.aarch64-unknown-freebsd.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9fc2ef269ab93e9eb29e2f452a56dd76d7df621b"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "023e853f975ab13595b3c6837424e7b6b5f6abf45df8d7c3ae7869d47ec3f91f"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.armv6l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87a9345bef8eb9708ca7c6ce0494e0988ea52b97"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "a850b023e8de43cba7f305369b0a8325866822b72ed6e1be909e8a97ef499bbd"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.armv6l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "faf094c2d04ebaa5c616aa5b46cd27518c16b843"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "a8db87d38b5848071f0ab0db7cd9635deae3e1e96d3d570f469d5ceba759f0f3"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.armv7l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a625e4bc3d588179e69ff2ac9853d4a859b070c"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "b080860efc1f795dd41d3e2f169a9b223819d572b981c05e22ffa015b08b2268"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.armv7l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "7835dc97120a2837cf0fce136c358b068d624c69"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "da7a804bea577f1fce1430ffe51fac85fd3ecd09e6bde48b0be1142708d7a8f4"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.i686-linux-gnu.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "c79891b1289095a3479da57d67369a212992a0d7"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "32f060515e3e854b2da50ed400f2a05ba5ca624beea1bc6f6226e76b708c5b49"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.i686-linux-musl.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "7edf7ab752be914cef1bba9a945df5a955800943"
os = "windows"

    [[GSL.download]]
    sha256 = "9d811cfda44c290f29b9f735ac05cf60f8d94ad4b34634bb27e83fdb3b7845e4"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.i686-w64-mingw32.tar.gz"
[[GSL]]
arch = "powerpc64le"
git-tree-sha1 = "d5a13feba25b6315d78f7e52cb91696092469401"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "d2379abfabc8e58b9bb9e8e15480248a3777f653efe742373c6a0edd5e23dab4"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.powerpc64le-linux-gnu.tar.gz"
[[GSL]]
arch = "riscv64"
git-tree-sha1 = "3d006fd63ac01ccd9d7ad61d9353b94f623ccab2"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "67e32a399494d2458dd0894878c9a3a6a0ceb6d0759059f433583f60acae908f"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.riscv64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "26f60a86f4ff22216a6cd993c9aaca2d48318435"
os = "macos"

    [[GSL.download]]
    sha256 = "3bb23fb8092234b7c2303ecbd488e06c5a688cdaaa66e4669593c20f52ab08e6"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.x86_64-apple-darwin.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "d8a3e90f6f2a82c1109a8e6730fdf674832db098"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "f479694c3344d891dbcd40a0657144bfed98390ef3688495c9b06f21270e517c"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.x86_64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "d96c3c4dae67227d9609281d9087e57d071edacb"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "1132914f471a5f52773acebe97865660e19fb4cd5b2b8863c748826a7f29d3b5"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.x86_64-linux-musl.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "f0fc230b3aec91538703b4dd1120348b61282967"
os = "freebsd"

    [[GSL.download]]
    sha256 = "e253dbfe55bc7c7133d2ac2ee921a0a860152eb0dbd21ca5509c92023d4680bf"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.x86_64-unknown-freebsd.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "ab7198eae99e4cfbc89d7b08fcc8db4f1973f248"
os = "windows"

    [[GSL.download]]
    sha256 = "fe1371237a4ccc57816aa8e34891811732ccb049b44400513b26697357b1794c"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.8.1+0/GSL.v2.8.1.x86_64-w64-mingw32.tar.gz"
