[[GSL]]
arch = "aarch64"
git-tree-sha1 = "3375f49f996fe8fc031b5cee44a6e4143b76bb6d"
os = "macos"

    [[GSL.download]]
    sha256 = "d7aec5ec562eab306c196e7945f72990c35f5d5dfc0188ea3f52f62765b133ff"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.aarch64-apple-darwin.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "6f95e81f014fe43f78cb13af5ed128791967c77c"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "d13b2f8e7fc6ddb0b143a7aee6e24224006d4a084a6bb13436959f2cb45264ff"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.aarch64-linux-gnu.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "0042bbffc9f54799080adcb11f228ffe7e880b81"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "f056a95322461014cbf4edcdcec43619ae47b1a6fcb53cd73cfed2c320db1bf0"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.aarch64-linux-musl.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "09740846373788bbf31d18a4f0f0e4d270d99d47"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "598a39b14de2dfa1586bd396272c3e99dcaad05a3f801b6b6a311afcb2fc017f"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.armv6l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc3555d9c12f35863ad65a29ff11a038ed11b1d1"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "05b771c702e120735445df1ec15ab164dfe7824ee5ba6ab1332686a5b5b20c86"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.armv6l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8e0ca835bfa2474aab0bb5b3dd123052b2922d7"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "bd12cfb54977309f90fb39feef6c927148695e46df947d4b5c0538f935fd27f2"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.armv7l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3943c6319afba7b11f48d11ca048f8ed8893cbd7"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "6e49a2b5e52a0c08273b146759c3042d87cb8cc83e09ee557cd1bfc1bb543e38"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.armv7l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "00c903423520ac318c71f272c97af46d3d48eb44"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "efdd1cbc4275f9040214a60814b2fc9db13be0d54ffcc4898f414f7243257ea3"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.i686-linux-gnu.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "e7fbf891b7f7993445a25831f1b7d6e48aad147d"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "3ae0e3401239faf3a20037143b9f90fd2e22bab92ff64ea7e3ad6820582ffd5e"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.i686-linux-musl.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "7334862987e4573f773c3829cc62d7c3f780d8f6"
os = "windows"

    [[GSL.download]]
    sha256 = "d3e1f6acb21fba61bf000f5b4e1ab97801926772e6db1e496a753c02d4691f16"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.i686-w64-mingw32.tar.gz"
[[GSL]]
arch = "powerpc64le"
git-tree-sha1 = "e93b26a5dda85d0a5de508a32f3d9e4c26d10919"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "730488b721b4147daee69125850664c776163bc7c977d3028619050ea15b962c"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.powerpc64le-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "a069bb65b0e7d78f08a0a342d84d12c2216de705"
os = "macos"

    [[GSL.download]]
    sha256 = "fe08277b9c75b72a652af33748da18be3154392d009d01bb5f8793a141a3ec9a"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.x86_64-apple-darwin.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "d159acf1739aafc829461d61aad66f5d718ce036"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "88a5d79a2a6c42a32126d71b47a9c921d2a9c8ca0ee1d76012720ffaee55f311"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.x86_64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "cb768b318a6f840be34aeb3c9a03854bdf088d47"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "fd7d349c77ce5e1ce4bcfe280d4cd4e5bcca13dcb471b81ccbbec44e7a641b27"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.x86_64-linux-musl.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "803acf6dc91d2813a7f4ad8a681839847928b6ed"
os = "freebsd"

    [[GSL.download]]
    sha256 = "4c898e3485e4103b9a3a1fed824ed2dc0bfc1e4a9461d81bac821d578a480272"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.x86_64-unknown-freebsd.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "1d01891c1edd6b312586f50124582fa609a004aa"
os = "windows"

    [[GSL.download]]
    sha256 = "eb642022539871c7991168492997c470d3176af6bd99386e262e16e50b45371d"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.2+0/GSL.v2.7.2.x86_64-w64-mingw32.tar.gz"
