[[GSL]]
arch = "aarch64"
git-tree-sha1 = "f129a1a312fac4f577720b9ec87a061475660fd2"
os = "macos"

    [[GSL.download]]
    sha256 = "9cd8636328fc07dd6c02cd8b8ad9595f4216313fb722eb3ed5d404ac7af5aaa2"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.aarch64-apple-darwin.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "c8b98267f8a4d7d7c21c47081957f68af5040157"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "ef963048787e044490dc03be28af5094254ccb5668ddc668181407aefbcb9517"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.aarch64-linux-gnu.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "af85d81b3f06b72dfa3eda676bc8157315607c34"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "28bd7ce5a8cd2152440d7058721a2bad67cd9234e7b781124a1d5daa9ba00a1e"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.aarch64-linux-musl.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "924f530e7e2f3b770966e293e186965501d465a9"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "67b10aac79e407e4f3ac5f64ca8ceea37e72d18bef93640702d78a42e2e0513e"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.armv6l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fbc29730f5fe44f5743e649d4f78b38f41849038"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "81506d20e00702e741214d6940fc4a626d3e46cbfe87c2019a0c0568ab5a5429"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.armv6l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e6d1e771512d7d5806b6f74e3afd76876a6295e"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "c5f1e293212dab990e0446e5f89db7f80dfdd8fa506378f1a916a0411ae7c089"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.armv7l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab437ae90d3ba2293a239d5f48a0a41de572512b"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "cac6b55e5aeec7ac4595da9010f4b0734938e11a2a4da090b90e9de8d8fe15e9"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.armv7l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "0cf1b272d11ba29e7c82d2982c130ff36dcbd8e0"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "59d74c30b1f2bc632fde84d393e47d4c3e8fb28939205624c885ba9fe22c97f4"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.i686-linux-gnu.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "772531c14410d905011b6556f386821ece4802dc"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "7d968bb20d8b134df77b9b0e455f9b5fa012c395c394c7f45bf0dfb3b4f2a237"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.i686-linux-musl.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "6d71ab3330a3145ada5c9f2ec0144db8ac0a5b1b"
os = "windows"

    [[GSL.download]]
    sha256 = "a0efea9e9200180bad1424df37ee4e50d6c10f86bf7b614086450370bc384436"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.i686-w64-mingw32.tar.gz"
[[GSL]]
arch = "powerpc64le"
git-tree-sha1 = "6bac8467b3246be544c3a728c808a884e0a1bc75"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "d8ef8d2a864a2ff5e9c5f8396a028c49ca6ef53c8c48274e914f0eca6c06893d"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.powerpc64le-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "91aea9766a14e681de18eab15395eebe3c177e17"
os = "macos"

    [[GSL.download]]
    sha256 = "3b34d8479f0f979e5856ff24df4937e11ccaa089709e607d23a5e9aeb09d3a14"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.x86_64-apple-darwin.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "3908767681eedc038a8c56d4c4ba2e1ca633e690"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "12b5b94344ccdce2720aa624b99fb39f43cf856af6283fedfdd6f903bcf0bcc0"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.x86_64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "59b765c39f85db045201506174083574abc8a2ab"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "c73503764e252f9a57ec4a3a37088325ab96c4fa3c39195d2666990fa9718e37"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.x86_64-linux-musl.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "ebfcf91bc9b2393cd4a16d6e647136e257a1c117"
os = "freebsd"

    [[GSL.download]]
    sha256 = "226957458183b17c56718fead83ca4b97fcc245db37df5a8ebb4183c2e9f1437"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.x86_64-unknown-freebsd.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "dab6352cdf6e6863d808ef8595841c240d9a3fb2"
os = "windows"

    [[GSL.download]]
    sha256 = "8da1aae1da6b8dd8cd4e3836120c054bddb7c2320a6315bee60d93eea1dcbcb6"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.1+0/GSL.v2.7.1.x86_64-w64-mingw32.tar.gz"
