[[GSL]]
arch = "aarch64"
git-tree-sha1 = "b2c246beed87893cd39973bd790679d29c464693"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "ea812249697167ce8a917939de715eaba565e3788b96ccda04d650b1c42c3893"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.aarch64-linux-gnu.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "6ad67c4afa872583c93cb4272830a0e833d0b1d2"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "e0ea9e0c381bb4df65addfac326abae862613e180ffb8ea0b0096080bd289054"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.aarch64-linux-musl.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a415c53fa043110b39aee91c64ac81e9b9ff1b1d"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "ae989ac9b382c4d4f56545654479a5a0ffcdf5e1cca76ddaf37c17ce15ed6b5b"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.armv7l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07c01389f80cd65b7659d333bbd25b4b1fbda817"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "c53acd90f623134e304613a1272e8c203d6315ae71c47d0f641a12f915bd9550"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.armv7l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "93412b6200b4c9a68cc85a05bc04c6c65c7b8452"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "24d7eaa512d219ca9670eb927407eefadb08a5eb38d7bf85e61977d293bd038d"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.i686-linux-gnu.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "066b63021ed1feaee569f1b4457fd483ca5f3e82"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "a3026bc38105ee767ac2d917a0b367ba84d327bb581949051b33bc14d144e2b8"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.i686-linux-musl.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "78793c19d6ee057c9904979693a17f25b39cd35f"
os = "windows"

    [[GSL.download]]
    sha256 = "9a57067bffe76b9efdfab7ccdb8ff534006e568be601ae42fe47b122b4f6d0c6"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.i686-w64-mingw32.tar.gz"
[[GSL]]
arch = "powerpc64le"
git-tree-sha1 = "592d6c01697f102cdef45632aa8ede5798f89511"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "a6d9d75a67411b7b6a95dd856adfb295bd07f882fb291ff7d6badaca074f8c5d"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.powerpc64le-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "60fd25d8121e64b7de21a4c6beca4a77c3f7136b"
os = "macos"

    [[GSL.download]]
    sha256 = "9fd2c5908063209db383a9c257cbf179cbf031610000e976795c78003c143093"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.x86_64-apple-darwin.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "a1da43a7770833fc05992df50a68c1eecd25b05b"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "7100b52f903c1bce6fe629dae0abdeefbbc2a86fc77f78bb4e0be621f5415bfd"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.x86_64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "3938f92ef6b345af5b5e0e9fc91cd144dec98b8e"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "ff20c9e9b51b86dc1d9fd70c06f1785a4280282f13aa9724f3c9ac6f2db64030"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.x86_64-linux-musl.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "ba0c518b8da32eaf3cd9a0f710ef8080adb35815"
os = "freebsd"

    [[GSL.download]]
    sha256 = "19cb697ccbdbc0d5229b7e38cdc7ffd3e5f0feaffc988db912dd47f694418725"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.x86_64-unknown-freebsd.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "d4a00da983a63e2a6e8fdaf36daea829aee9d1e8"
os = "windows"

    [[GSL.download]]
    sha256 = "9b21c077b055ae04e71c8e070ebc4a10eb22085d99dd6785e20f47925b92d4eb"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.7.0+0/GSL.v2.7.0.x86_64-w64-mingw32.tar.gz"
