[[GSL]]
arch = "i686"
git-tree-sha1 = "78d560a67ed320be1ff00068805b7adb40edf4f7"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "871d784f4fd06987d7a28a495492a9c2bd91a76a1c22531639485fa2f7f0a5df"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.i686-linux-musl.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "26c220f735e2df22d4518dc66d547e072cf297b3"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "af054ea504421e31876bc0cf4c876c357f4a2fd7ae08432bd22bf97cf4364f2f"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.aarch64-linux-musl.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "62cf7fd94852ef8d4245c624e53927aa3d0aaf4a"
os = "windows"

    [[GSL.download]]
    sha256 = "9fcfcd4a3b8f600d1e0c24a2082f9bd1948608ff8c8715a873ca8688b7621429"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.i686-w64-mingw32.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "abb59c0fd1252e02b06dd01a0b2a9f656993cddd"
os = "windows"

    [[GSL.download]]
    sha256 = "caa5cc87daefb4fb2b66b78773ffa67c8f51440a8c0a85cf17f2e744806d9f21"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.x86_64-w64-mingw32.tar.gz"
[[GSL]]
arch = "armv7l"
git-tree-sha1 = "7d555b477f7c064f652cd2029c94444c19de2afb"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "2f87492f02e7b675fde4f798e46b779fba1e126a6770670f57825c369a402290"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.armv7l-linux-gnueabihf.tar.gz"
[[GSL]]
arch = "armv7l"
git-tree-sha1 = "789d32500cca21a7edeb721b9ce1c1fcf71e8aba"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "13149bcc1769bb4e25ca177d8ba6679a4155c27a062bc887c79e547df20a76e6"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.armv7l-linux-musleabihf.tar.gz"
[[GSL]]
arch = "i686"
git-tree-sha1 = "87753ef4e807f131d5c9d6017765d3f68d9183c9"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "521aba1771dba0fda8344f847c99f881a95aee76950310c9773bbd0846b2f771"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.i686-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "114f293131466f68f26f24644a9350d1a4a9e6ca"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "e099fc91f0c54a7ce84109c38980116a7bd2193cceba7cd846097571cb534c91"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.x86_64-linux-gnu.tar.gz"
[[GSL]]
arch = "powerpc64le"
git-tree-sha1 = "319cd87bd3261361addd9c0602e2c8cb0d426811"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "06adf33646a4ba557d65c33146351cfb026a85e2c7f1de9db48adb63f5af8c69"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.powerpc64le-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "3f94cd30651293156bf4dab0abc47e481addd9d6"
os = "macos"

    [[GSL.download]]
    sha256 = "4323e9aa75cf340978c8233574359a3cadb18432d620865242dd0b46f865024c"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.x86_64-apple-darwin14.tar.gz"
[[GSL]]
arch = "aarch64"
git-tree-sha1 = "400aa0aab1758da4ceccf70e1e4024eb6dd623ea"
libc = "glibc"
os = "linux"

    [[GSL.download]]
    sha256 = "596754f1496de43411a10c4b83d2dd47c98bb91808afa1844863735431549080"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.aarch64-linux-gnu.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "b033e6026630c0b6eeafde77c52b3b39e8fb0704"
os = "freebsd"

    [[GSL.download]]
    sha256 = "d136a19626b5949f9f77f4f8c20f0ef5902513781c85d90b3a536a79515f514e"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.x86_64-unknown-freebsd11.1.tar.gz"
[[GSL]]
arch = "x86_64"
git-tree-sha1 = "b7b216c8ba0afd4770270080f665fed9502206c4"
libc = "musl"
os = "linux"

    [[GSL.download]]
    sha256 = "c75e69f1fe419567e9d9e96658d2d1d5a5aee8ed70c72b506f5d59dee91cd263"
    url = "https://github.com/JuliaBinaryWrappers/GSL_jll.jl/releases/download/GSL-v2.6.0+3/GSL.v2.6.0.x86_64-linux-musl.tar.gz"
